# -*- coding: utf-8 -*-
"""carlacode1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UV7GLe0Lau6Pkfk0uNuBhnOLX-6MKdcs
"""

import glob
import os
import sys
import cv2
import random
import matplotlib.pyplot as plt
import time
import numpy as np
import argparse
import carla

try:
    sys.path.append(glob.glob('../carla/dist/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

def main():
  client = carla.Client('localhost', 2000)
  client.set_timeout(10.0) # seconds
  world = client.load_world("Town02")
  print(client.get_available_maps())

if __name__ == '__main__':

    try:
        main()
    except KeyboardInterrupt:
        print('\nCancelled by user. Bye!')
    except RuntimeError as e:
        print(e)